some formatting

diff --git a/cron/crontest b/cron/crontest
--- a/cron/crontest
+++ b/cron/crontest
@@ -6,7 +6,7 @@
 #
 #  1. When adding your cron job, use all 5 stars to make it run every minute
 #  2. Wrap the command in crontest
-#        
+#
 #
 #  Example:
 #
@@ -14,10 +14,10 @@
 #     * * * * * /usr/local/bin/crontest $HOME/bin/my-new-script --myparams
 #
 #  Now, cron will run your job every minute, but crontest will only allow one
-#  instance to run at a time.  
+#  instance to run at a time.
 #
 #  crontest always wraps the command in "screen -D -m" if possible, so you can
-#  use "screen -x" to attach and interact with the job.   
+#  use "screen -x" to attach and interact with the job.
 #
 #  If --bashdb is used, the command line will be passed to bashdb.  Thus you
 #  can attach with "screen -x" and debug the remaining command in context.
@@ -33,9 +33,9 @@
 #
 
 crontestLog=/tmp/crontest.log
-lockfile=$(if [[ -d /var/lock ]]; then echo /var/lock/crontest.lock; else echo /tmp/crontest.lock; fi )
+lockfile=$(if [[ -d /var/lock ]]; then echo /var/lock/crontest.lock; else echo /tmp/crontest.lock; fi)
 useBashdb=false
-useScreen=$( if which screen &>/dev/null; then echo true; else echo false; fi )
+useScreen=$(if which screen &>/dev/null; then echo true; else echo false; fi)
 innerArgs="$@"
 screenBin=$(which screen 2>/dev/null)
 
@@ -44,42 +44,42 @@ function errExit {
 }
 
 function log {
-	echo "[-stat-] $@" >> $crontestLog
+	echo "[-stat-] $@" >>$crontestLog
 }
 
 function parseArgs {
 	while [[ ! -z $1 ]]; do
 		case $1 in
-			--bashdb)
-				if ! $useScreen; then
-					errExit "--bashdb invalid in crontest because GNU screen not installed"
-				fi
-				if ! which bashdb &>/dev/null; then
-					errExit "--bashdb invalid in crontest: no bashdb on the PATH"
-				fi
+		--bashdb)
+			if ! $useScreen; then
+				errExit "--bashdb invalid in crontest because GNU screen not installed"
+			fi
+			if ! which bashdb &>/dev/null; then
+				errExit "--bashdb invalid in crontest: no bashdb on the PATH"
+			fi
 
-				useBashdb=true
-				;;
-			--)
-				shift
-				innerArgs="$@"
-				return 0
-				;;
-			*)
-				innerArgs="$@"
-				return 0
-				;;
+			useBashdb=true
+			;;
+		--)
+			shift
+			innerArgs="$@"
+			return 0
+			;;
+		*)
+			innerArgs="$@"
+			return 0
+			;;
 		esac
 		shift
 	done
 }
 
-if [[ -z  $sourceMe ]]; then
+if [[ -z $sourceMe ]]; then
 	# Lock the lockfile (no, we do not wish to follow the standard
 	# advice of wrapping this in a subshell!)
 	exec 9>$lockfile
 	flock -n 9 || exit 1
-	
+
 	# Zap any old log data:
 	[[ -f $crontestLog ]] && rm -f $crontestLog
 
@@ -89,12 +89,12 @@ if [[ -z  $sourceMe ]]; then
 	log "Raw command line: $@"
 	log "Inner args: $@"
 	log "screenBin: $screenBin"
-	log "useBashdb: $( if $useBashdb; then echo YES; else echo no; fi )"
-	log "useScreen: $( if $useScreen; then echo YES; else echo no; fi )"
-	
+	log "useBashdb: $(if $useBashdb; then echo YES; else echo no; fi)"
+	log "useScreen: $(if $useScreen; then echo YES; else echo no; fi)"
+
 	# Were building a command line.
 	cmdline=""
-	
+
 	# If screen is available, put the task inside a pseudo-terminal
 	# owned by screen.  That allows the developer to do a "screen -x" to
 	# interact with the running command:
@@ -114,19 +114,15 @@ if [[ -z  $sourceMe ]]; then
 
 	log "cmdline: $cmdline"
 
-
 	# And run the whole schlock:
-	$cmdline 
+	$cmdline
 
 	res=$?
 
 	log "Command result: $res"
 
-
-	echo "[-result-] $(if [[ $res -eq 0 ]]; then echo ok; else echo fail; fi)" >> $crontestLog
+	echo "[-result-] $(if [[ $res -eq 0 ]]; then echo ok; else echo fail; fi)" >>$crontestLog
 
 	# Release the lock:
 	9<&-
 fi
-
-
